spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #不校验流程文件，默认是开启的
  activiti:
    check-process-definitions: false
    #数据结构更新，默认是开启的，
    database-schema-update: true
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    #通过进入源码发现默认是audit级别
    history-level: full
    #自动创建、更新、验证数据库表结构
    #扫描processes下的流程文件 ，通过源码发现默认是这样扫描的
    process-definition-location-prefix: classpath:/processes/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10000MB
      max-request-size: 10000MB
